<template>
    <v-container>
    <v-row
      class="mb-6"
      no-gutters
    >
        <v-col>
            <h1 class="display-1 text-center">Free Chat</h1>
        </v-col>
    </v-row>
    <v-row
      class="mb-6"
      no-gutters
    >
      <v-col md="4">
        <v-card
          class="pa-2"
          outlined
          tile
        >
         <v-card-title>Send</v-card-title>
           <v-card-actions>
              <v-btn
                    outlined
                    text
                    block
                    to="/send"
                >
                    Send
                </v-btn>
          </v-card-actions>
        </v-card>
      </v-col>
      <v-col
        md="4"
        offset-md="4"
      >
        <v-card
          class="pa-2"
          outlined
          tile
        >
        <v-card-title>Receive</v-card-title>
          <v-card-actions>
              <v-btn
                    outlined
                    text
                    block
                    to="/receive"
                >
                    Receive
                </v-btn>
          </v-card-actions>
        </v-card>
      </v-col>
    </v-row>
    </v-container>
</template>